### PR TITLE
Improve the way Slack digest messages are "chunked"

### PR DESCRIPTION
**Pull request by cjsauer**
Note that this PR encapsulates _both_ of the following Trello cards.

Card: https://trello.com/c/PXMgjBzh/1994-change-how-slack-digest-messages-are-chunked

Relevant sentry exception fixed in this PR: https://sentry.io/organizations/opencompany/issues/981121572/?project=81593&query=is%3Aunresolved

To test:

1. Clear out your local databases (rethink and dynamo) and restart services
2. Onboard owner user via slack (org 1)
3. **Delete sample messages**. We need to test the case of 0 digest messages.
4. Enable the slack bot
5. Invite an email address that you own via email onboard (we will test email digest for regressions shortly)
6. Onboard member user via slack (org 1)
7. In the browser housing your owner user's session, visit the [run slack digest][1] link to force a digest run. Check slack/logs to **make sure that no messages are sent**.
8. Perform the same test in your member user's browser session.
9. Create a regular post (not must-see) using either member, rerun the slack digest, and observe that the digest in slack **contains only 1 message** with banner, post, and footer block all in one message (it's helpful to select a different channel in Slack before running the digest so that you can observe the notification badge count).
10. Create a must-see post using either member, rerun the slack digest, and observe that the digest in slack **contains 2 messages**, and that the "must see" post is above the first post (i.e. sorted by priority).
11. Create a third regular post (not must-see) with either member **in a different board**, rerun the slack digest, and observe that the digest **contains 3 separate messages**, and that this new post is sorted alphabetically by board name (but still below the must-see post).
12. Create a fourth regular post (non must-see) with either member **in the same board as the last test**, rerun the slack digest, and observe that the digest **contains 4 messages**, and that this new post is sorted below the last post (i.e. sorted by time)
13. In your member user's browser session, tab away from Carrot so that posts are not viewed on FoC. Create a few posts with your owner user, and then run the member user's digest. Ensure that "you have viewed this post" **is not preset** on the new posts you just made. If you're testing in a Carrot 2.0 environment (you should!) then do the exact opposite of this test (i.e. mark posts as read).
14. Onboard the user that you invited via email in a different browser session, and [run their email digest][2]. Ensure that you receive the email digest, and that it is properly formatted/sorted (nothing in this PR should affect the email digest, so this is a regression test).

[1]: http://localhost:3008/_/slack/run
[2]: http://localhost:3008/_/email/run

### CODE REVIEW

**Comment by cjsauer** [comment]
[Slack related exceptions](https://trello.com/c/648yX7oP/2006-slack-related-exceptions)

**Comment by cjsauer** [comment]
[Change how Slack digest messages are "chunked"](https://trello.com/c/PXMgjBzh/1994-change-how-slack-digest-messages-are-chunked)

**Comment by belucid** [comment]
@cjsauer is this ready for review?

**Comment by cjsauer** [comment]
@belucid yeah, sorry. Moved the card but didn't add the label.

**Pull request merged**
