### PR TITLE
Slack reminders design

### PR DESCRIPTION
**Pull request by thepug**
[Trello](https://trello.com/c/hNUSWZHo)

Abstract https://app.goabstract.com/share/5f22939b-1411-4f9b-b069-d6c2daf7d7b2

Changes reminder to look like the above.

To test:
- create a reminder
- [x] does the notification look like the abstract?

### CODE REVIEW

**Comment by thepug** [comment]
[Slack reminders design changes](https://trello.com/c/hNUSWZHo/1863-slack-reminders-design-changes)

**Comment by bago2k4** [comment]
Needs to add AM/PM to the time of the notification, right now it shows only the hour (no minutes too).

screenshot 2019-02-20 at 1 31 59 pm

**Comment by bago2k4** [comment]
EC: so we decided to remove the time from the notification since the users can't change it and if possible turn the reminder title into a link

**Comment by bago2k4** [comment]
So @thepug about the data we decided that makes sense to have the day of week (mon, tue etc..) only for weekly and biweekly options. For monthly and quarterly we should show something like: first day of quarter or last day of month etc...
The options are:
- first day of period (month or quarter)
- first monday of period
- last day of period
- last friday of period

please check that the copy can fit on that sentence (i didn't check all of them)

**Comment by belucid** [comment]
@thepug  and @bago2k4, I asked Ryan about the reminder created notification design: https://opencompanyhq.slack.com/archives/C0AEP1RS9/p1550759848076800

**Pull request merged**
