### PR TITLE
Update readme with S3 bucket naming fix and notices

### PR DESCRIPTION
**Pull request by cjsauer**
I was running into "bucket not found" errors while setting this service up locally, and noticed that the keywords used in `config.clj` are actually different than what's noted in the readme. 

I've updated the readme, and renamed my buckets in S3, only to run into "access denied" errors. Turning off all public access blocks (S3 -> click a bucket -> permissions tab -> public access settings -> uncheck all boxes) seems to have fixed the issue, but I'm not sure if this is the intended approach...**Please advise**.

Trello card: https://trello.com/c/TdaMbhHv/2016-fix-readme-inaccuracies-in-bot-service-repository

### CODE REVIEW

**Comment by cjsauer** [comment]
[Fix readme inaccuracies in bot service repository](https://trello.com/c/TdaMbhHv/2016-fix-readme-inaccuracies-in-bot-service-repository)

**Comment by cjsauer** [comment]
@bago2k4 I've updated the readme to match your suggestions. What are your thoughts regarding:

>I've updated the readme, and renamed my buckets in S3, only to run into "access denied" errors. Turning off all public access blocks (S3 -> click a bucket -> permissions tab -> public access settings -> uncheck all boxes) seems to have fixed the issue, but I'm not sure if this is the intended approach...Please advise.

I think I should add a note to the readme about bucket permissions, but I'm not sure this solution is "correct".

**Comment by cjsauer** [comment]
@bago2k4 readme has been updated with notes from our slack discussion. Should be ready for merge unless you have any further comments.

**Comment by bago2k4** [comment]
Looks good to me, merging...

**Pull request merged**
