### PR TITLE
Company logo from Slack if present

### PR DESCRIPTION
**Pull request by martinklepsch**
[trello card](https://trello.com/c/2sNLCroN/486-include-team-s-logo-from-slack-as-company-logo-in-new-company-creation-flow) & [trello card](https://trello.com/c/QTeRaScu/495-update-onboarding-script-to-update-logo-rather-than-name)

- The onboarding conversation now checks the company's logo instead of its name
- if a custom logo has been specified in Slack the user can confirm it or provide an alternative
- if no logo is specified the user may supply one

To Test:

- [x] sign in
- [x] create a company
- [x] go through the onboarding conversation initiated with the slack account who created the company
- [x] update the logo and try other permutations of the conversation
- [x] verify the logo has been updated in the database/web

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing

**Comment by belucid** [comment]
@martinklepsch image validation doesn't seem to be working. Tried these:

https://media.giphy.com/media/xTiTnlgsJTVPK9hGZa/giphy.gif
http://media.giphy.com/media/xTiTnlgsJTVPK9hGZa/giphy.gif
https://pbs.twimg.com/profile_images/700577267127193600/PtLt3m6R.png
http://pbs.twimg.com/profile_images/700577267127193600/PtLt3m6R.png

All failed with something like:

```
16-06-21 14:07:09 Seans-Mac-Pro.local ERROR [oc.bot.language:37] - The following URL caused an exception while checking {:url "http://pbs.twimg.com/profile_images/700577267127193600/ptlt3m6r.png"}
                                 java.lang.Thread.run            Thread.java:  745
                                                  ...
             manifold.executor/thread-factory/reify/f           executor.clj:   36
             io.aleph.dirigiste.Executor$Worker$1.run          Executor.java:   62
                    io.aleph.dirigiste.Executor$3.run          Executor.java:  308
                                                  ...
                     manifold.deferred.Deferred/fn/fn           deferred.clj:  398
                 manifold.deferred.Listener/onSuccess           deferred.clj:  219
              manifold.deferred/eval2551/subscribe/fn           deferred.clj:  716
                   manifold.deferred/eval2551/chain'-           deferred.clj:  752
                   manifold.deferred/eval2551/chain'-           deferred.clj:  737
                           manifold.deferred/success!           deferred.clj:  243
                   manifold.deferred.Deferred/success           deferred.clj:  396
                        manifold.deferred.Deferred/fn           deferred.clj:  396
                 manifold.deferred.Listener/onSuccess           deferred.clj:  219
              manifold.deferred/eval2551/subscribe/fn           deferred.clj:  710
                   manifold.deferred/eval2551/chain'-           deferred.clj:  737
                           manifold.deferred/success!           deferred.clj:  243
                   manifold.deferred.Deferred/success           deferred.clj:  396
                        manifold.deferred.Deferred/fn           deferred.clj:  396
                 manifold.deferred.Listener/onSuccess           deferred.clj:  219
              manifold.deferred/eval2551/subscribe/fn           deferred.clj:  716
                   manifold.deferred/eval2551/chain'-           deferred.clj:  755
                           manifold.deferred/success!           deferred.clj:  243
                   manifold.deferred.Deferred/success           deferred.clj:  396
                        manifold.deferred.Deferred/fn           deferred.clj:  396
                 manifold.deferred.Listener/onSuccess           deferred.clj:  219
              manifold.deferred/eval2551/subscribe/fn           deferred.clj:  716
                   manifold.deferred/eval2551/chain'-           deferred.clj:  755
                           manifold.deferred/success!           deferred.clj:  243
                   manifold.deferred.Deferred/success           deferred.clj:  396
                        manifold.deferred.Deferred/fn           deferred.clj:  396
                 manifold.deferred.Listener/onSuccess           deferred.clj:  219
              manifold.deferred/eval2551/subscribe/fn           deferred.clj:  716
                   manifold.deferred/eval2551/chain'-           deferred.clj:  755
                           manifold.deferred/success!           deferred.clj:  243
                   manifold.deferred.Deferred/success           deferred.clj:  396
                        manifold.deferred.Deferred/fn           deferred.clj:  396
                 manifold.deferred.Listener/onSuccess           deferred.clj:  219
              manifold.deferred/eval2551/subscribe/fn           deferred.clj:  716
                   manifold.deferred/eval2551/chain'-           deferred.clj:  755
                           manifold.deferred/success!           deferred.clj:  243
                   manifold.deferred.Deferred/success           deferred.clj:  396
                        manifold.deferred.Deferred/fn           deferred.clj:  396
                 manifold.deferred.Listener/onSuccess           deferred.clj:  219
              manifold.deferred/eval2551/subscribe/fn           deferred.clj:  710
                   manifold.deferred/eval2551/chain'-           deferred.clj:  737
                           manifold.deferred/success!           deferred.clj:  243
                   manifold.deferred.Deferred/success           deferred.clj:  396
                        manifold.deferred.Deferred/fn           deferred.clj:  396
                 manifold.deferred.Listener/onSuccess           deferred.clj:  219
                            manifold.deferred/zip'/fn           deferred.clj: 1056
                           manifold.deferred/success!           deferred.clj:  243
                   manifold.deferred.Deferred/success           deferred.clj:  396
                        manifold.deferred.Deferred/fn           deferred.clj:  396
                 manifold.deferred.Listener/onSuccess           deferred.clj:  219
              manifold.deferred/eval2551/subscribe/fn           deferred.clj:  716
                   manifold.deferred/eval2551/chain'-           deferred.clj:  750
   aleph.http.client-middleware/wrap-exceptions/fn/fn  client_middleware.clj:  179
                   manifold.deferred/eval2551/chain'-           deferred.clj:  770
                   manifold.deferred/eval2551/chain'-           deferred.clj:  750
aleph.http.client-middleware/wrap-exceptions/fn/fn/fn  client_middleware.clj:  183
                                 clojure.core/ex-info               core.clj: 4617
clojure.lang.ExceptionInfo: status: 404
           body: #object[java.io.ByteArrayInputStream 0x497dad06 "java.io.ByteArrayInputStream@497dad06"]
       complete: #<SuccessDeferred@5f25a53a: false>
        headers: {"x-cache" "MISS",
                  "server" "ECS (atl/5D9D)",
                  "content-type" "image/png",
                  "access-control-allow-origin" "*",
                  "x-content-type-options" "nosniff",
                  "content-length" "4458",
                  "x-connection-hash" "3e25287297597efec1dc8228a5d4c384",
                  "x-response-time" "8",
                  "date" "Tue, 21 Jun 2016 14:07:09 GMT",
                  "x-xss-protection" "1; mode=block",
                  ...}
    keep-alive?: true
         status: 404
```

**Comment by belucid** [comment]
@martinklepsch also we discussed in chat specific bot language for an image it can't get. The generic "I'm not sure what to do with this." isn't good there.

**Comment by belucid** [comment]
@martinklepsch we have `:company/logo :yes-after-update` and `:company/logo :yes` in the script, but they don't seem to distinguish anything. It always goes to `:company/logo :yes-after-update` no matter if there was an update or not.

 [:company/logo :yes-after-update]
 ["Cool, got it."
  "Good work {{user/name}}, your new OpenCompany dashboard is ready at: {{env/origin}}/{{company/slug}} You may need to refresh your dashboard to see your new logo."
  "Now it’s easy to keep your team, investors and other stakeholders engaged and up to date."]
 [:company/logo :yes]
 ["Great. We'll keep the image as is."
  "Good work {{user/name}}, your new OpenCompany dashboard is ready at: {{env/origin}}/{{company/slug}}"
  "Now it’s easy to keep your team, investors and other stakeholders engaged and up to date."]
}

**Comment by martinklepsch** [comment]
@belucid I updated this to improve the messages in case a message can't be understood. I haven't tested it yet. Is there anything else that we discussed that should be changed?

**Comment by belucid** [comment]
Reviewing.

**Pull request merged**
