### PR TITLE
Interaction data in slack digest.

### PR DESCRIPTION
**Pull request by thepug**
### Review after https://github.com/open-company/open-company-digest/pull/17

To test: 

- create a post and add a reaction and comment
- run the digest for slack
- [x] does the digest have the comments and reactions?

### CODE REVIEW

**Comment by thepug** [comment]
[Reaction data in slack](https://trello.com/c/y5ZgayiL/1852-reaction-data-in-slack)

**Comment by bago2k4** [comment]
@thepug this logic will be used by email too right? maybe it's better to move it to lib now or you wanted to wait to see what's needed and what not by email?

**Comment by thepug** [comment]
> @thepug this logic will be used by email too right? maybe it's better to move it to lib now or you wanted to wait to see what's needed and what not by email?

Yeah I wasn't sure about email and wanted to get it right in the bot first.

**Comment by thepug** [comment]
@bago2k4 forgot that this is dependent on this PR https://github.com/open-company/open-company-digest

**Comment by thepug** [comment]
need to oder the list of names where `You` is always first.

**Comment by belucid** [comment]
We lose the WST attachment when there are comments.

**Pull request merged**
