### PR TITLE
Digest design

### PR DESCRIPTION
**Pull request by thepug**
Changes the introduction message.
Adds a banner with orgs logo.
Changes the author title.
Adds a view  post button.

To test:

- create a new post
- run the slack digest as your logged user by visiting http://localhost:3008/_/slack/run
- [x] do you get a digest with the changes?

### Needs infra PR: https://github.com/belucid/open-company-infrastructure/pull/97

### CODE REVIEW

**Comment by thepug** [comment]
[Slack digest changes](https://trello.com/c/8lt1nRXi/1792-slack-digest-changes)

**Comment by bago2k4** [comment]
@thepug another thing is that the image is added with a white band on the left that is invisible when the message is in the normal state but is visible when you hover the message.
Do you think it's possible to add the image in another way (with another field or format the text of the message to have the image url but don't show it)?
I checked the postMessage api and doesn't seem so, just asking if you know better

**Comment by belucid** [comment]
@bago2k4 there was a long discussion in Slack about the white band. It's the best we can do for now w/o Block Kit.

**Comment by thepug** [comment]
@bago2k4 The code is suppose to wait when the `s3transfer/upload` function finishes. It doesn't mean that the file is ready on s3 when that function finishes.  Without adding complications such as processing events from s3, I don't see an easy way to fix this.

> the first time i run the digest and the image was generated it wasn't visible in Slack: my guess is that Slack read it too soon and it wasn't available yet, not sure though...

**Comment by thepug** [comment]
need to handle missing logo

**Comment by bago2k4** [comment]
@thepug here is the fix for the public bucket using put-object (git diff):
```
$ git diff src/oc/bot/image.clj
diff --git a/src/oc/bot/image.clj b/src/oc/bot/image.clj
index 3976faa..3df3d4f 100644
--- a/src/oc/bot/image.clj
+++ b/src/oc/bot/image.clj
@@ -1,7 +1,7 @@
 (ns oc.bot.image
   (:require [clj-http.client :as http]
             [clojure.java.io :as io]
-            [amazonica.aws.s3transfer :as s3]
+            [amazonica.aws.s3 :as s3]
             [oc.bot.config :as c])
   (:import  [java.io File]
             [java.net URL]
@@ -29,11 +29,16 @@
 (defn write-to-s3
   [org-slug]
   ;; put object with client side encryption
-  (s3/upload
-    c/slack-digest-s3-bucket
-    (str org-slug ".png")
-    (File. (tmp-file org-slug)))
-  (Thread/sleep 5000))
+  (s3/put-object
+    {:access-key c/aws-access-key-id
+     :secret-key c/aws-secret-access-key}
+    :bucket-name c/slack-digest-s3-bucket
+    :key (str org-slug ".png")
+    :file (File. (tmp-file org-slug))
+    :access-control-list {
+     :grant-all [
+      ["AllUsers" "Read"]
+      ["AuthenticatedUsers" "Write"]]}))

 (defn- org-logo [logo]
   (if logo
```

We can change the buckets back to not public and write objects as public.

**Comment by bago2k4** [comment]
@thepug do we need to add the white background frame for the logos or not? Not sure what we decided on the call friday.

**Comment by bago2k4** [comment]
NB: @thepug we need to recreate the buckets to not be public or the `put-object` with credentials will fail.

**Comment by bago2k4** [comment]
Ignoring eastwood linting errors, going to fix those with #56

**Pull request merged**
